---

kube-prometheus-stack:
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      paths: 
        - /prometheus
      hosts:
        - helm-charts.ceems.dev

    prometheusSpec:
      routePrefix: /prometheus

  grafana:
    env:
      GF_DATAPROXY_SEND_USER_HEADER: true
      GF_SERVER_ROOT_URL: http://localhost:3000/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: true

    ingress:
      enabled: true
      ingressClassName: nginx
      path: /grafana
      hosts:
        - helm-charts.ceems.dev

pyroscopeServer:
  enabled: true

pyroscope:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - helm-charts.ceems.dev
