---

ceemsExporter:
  collectors:
    emissions:
      deploy:
        networkPolicy:
          enabled: true
          ingress:
            - from:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/name: prometheus
          egress:
            - {}

  networkPolicy:
    enabled: true
    ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
    egress:
      - {}

ceemsAPIServer:
  networkPolicy:
    enabled: true
    ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
    egress:
      - {}

ceemsLB:
  networkPolicy:
    enabled: true
    ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
    egress:
      - {}

kube-prometheus-stack:
  prometheus:
    networkPolicy:
      enabled: true
      ingress:
        - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: grafana
        - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: kube-ceems-api-server
        - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: kube-ceems-lb
      egress:
        - {}
