---
# This scenario shows how to use network policies to restrict
# the access to CEEMS components and Prometheus web server.

ceemsExporter:
  collectors:
    emissions:
      deploy:
        # Enable network policy for emissions exporter.
        networkPolicy:
          enabled: true
          # Allow ingress only from Prometheus
          ingress:
            - from:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/name: prometheus
          # Allow ALL egress
          egress:
            - {}

  # Enable network policy for CEEMS exporter daemonset.
  networkPolicy:
    enabled: true
    # Allow ingress only from Prometheus
    ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
    # Allow ALL egress
    egress:
      - {}

ceemsAPIServer:
  # Enable network policy for CEEMS API server
  networkPolicy:
    enabled: true
    # Allow ingress from Grafana
    ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
    # Allow ALL egress
    egress:
      - {}

ceemsLB:
  # Enable network policy for CEEMS LB
  networkPolicy:
    enabled: true
    # Allow ingress from Grafana
    ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
    # Allow ALL egress
    egress:
      - {}

kube-prometheus-stack:
  prometheus:
    # Enable network policy for Prometheus
    networkPolicy:
      enabled: true
      # Allow ingress from Grafana, CEEMS API server and CEEMS LB
      ingress:
        - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: grafana
        - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: kube-ceems-api-server
        - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: kube-ceems-lb
      # Allow ALL egress
      egress:
        - {}
