---

ceemsExporter:
  collectors:
    redfish:
      enabled: true
      chassisNames:
        - Chassis_1
      config:
        protocol: http
        hostname: RUNNER_IP
        port: 5000
        username: admin
        password: somesupersecret

redfishProxy:
  enabled: true

  kubeRBACProxy:
    enabled: true
