{{- if and .Values.ceemsAPIServer.rbac.create .Values.ceemsAPIServer.enabled }}
{{- if or .Values.ceemsAPIServer.kubeRBACProxy.enabled .Values.monitorCurrentCluster (gt (len .Values.ceemsAPIServer.rbac.extraClusterRoleRules) 0) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kube-ceems.api-server.labels" . | nindent 4 }}
  name: {{ template "kube-ceems.api-server.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-ceems.api-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kube-ceems.api-server.serviceAccountName" . }}
  namespace: {{ template "kube-ceems.api-server.namespace" . }}
{{- end }}
{{- end }}
