{{- if and .Values.ceemsAPIServer.enabled (index .Values "ceems-api-server" "grafana" "datasource" "create") }}
{{- $basicAuthEnabled := (and (hasKey (index .Values "ceems-api-server" "grafana" "datasource" "basicAuth") "username") (hasKey (index .Values "ceems-api-server" "grafana" "datasource" "basicAuth") "password")) -}}
{{- $authHeaderEnabled := (and (hasKey (index .Values "ceems-api-server" "grafana" "datasource" "authHeader") "name") (hasKey (index .Values "ceems-api-server" "grafana" "datasource" "authHeader") "value")) -}}
{{- $tlsEnabled := (and (hasKey (index .Values "ceems-api-server" "grafana" "datasource" "tls") "clientCert") (hasKey (index .Values "ceems-api-server" "grafana" "datasource" "tls") "clientKey")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-api-server.fullname" (index .Subcharts "ceems-api-server") }}-grafana-ds
  namespace: {{ include "ceems-api-server.namespace" (index .Subcharts "ceems-api-server") }}
  labels:
    {{ tpl (index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label") . }}: {{ tpl (index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "labelValue") . }}
    {{- include "ceems-api-server.labels" (index .Subcharts "ceems-api-server") | nindent 4 }}
stringData:
  ceems-api-server.yaml: |-
    apiVersion: 1
    datasources:
      - name: {{ template "ceems-api-server.fullname" (index .Subcharts "ceems-api-server") }}
        type: yesoreyeram-infinity-datasource
        url: {{ index .Values "ceems-api-server" "grafana" "datasource" "scheme" }}://{{ template "ceems-api-server.fullname" (index .Subcharts "ceems-api-server") }}.{{ template "ceems-api-server.namespace" (index .Subcharts "ceems-api-server") }}:{{ index .Values "ceems-api-server" "service" "port" }}
{{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ index .Values "ceems-api-server" "grafana" "datasource" "basicAuth" "username" }}
{{- end }}
        jsonData:
{{- if $basicAuthEnabled }}
          auth_method: basicAuth
{{- end }}
          tlsSkipVerify: {{ (index .Values "ceems-api-server" "grafana" "datasource" "tls" "skipVerify") | default false }}
          tlsAuth: {{ (index .Values "ceems-api-server" "grafana" "datasource" "tls" "authEnabled") | default false }}
          tlsAuthWithCACert: {{ (index .Values "ceems-api-server" "grafana" "datasource" "tls" "authWithCACert") | default false }}
          timeout: 120
          allowedHosts:
            - {{ index .Values "ceems-api-server" "grafana" "datasource" "scheme" }}://{{ template "ceems-api-server.fullname" (index .Subcharts "ceems-api-server") }}.{{ template "ceems-api-server.namespace" (index .Subcharts "ceems-api-server") }}:{{ index .Values "ceems-api-server" "service" "port" }}
          httpHeaderName1: X-Grafana-User
{{- if $authHeaderEnabled }}
          httpHeaderName2: {{ index .Values "ceems-api-server" "grafana" "datasource" "authHeader" "name" }}
{{- end }}
        secureJsonData:
          # This will be replaced by username before passing to API server
          # This feature is available only for yesoreyeram-infinity-datasource >= 3.x
          # IMPORTANT: Need $$ to escape $
          httpHeaderValue1: $${__user.login}
{{- if $basicAuthEnabled }}
          basicAuthPassword: {{ index .Values "ceems-api-server" "grafana" "datasource" "basicAuth" "password" }}
{{- end }}
{{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ index .Values "ceems-api-server" "grafana" "datasource" "authHeader" "value" }}
{{- end }}
{{- if $tlsEnabled }}
          tlsCACert: {{ (index .Values "ceems-api-server" "grafana" "datasource" "tls" "caCert") | toYaml | indent 10 }}
          tlsClientCert: {{ (index .Values "ceems-api-server" "grafana" "datasource" "tls" "clientCert") | toYaml | indent 10 }}
          tlsClientKey: {{ (index .Values "ceems-api-server" "grafana" "datasource" "tls" "clientKey") | toYaml | indent 10 }}
{{- end }}
{{- end }}
