{{- if and .Values.ceemsAPIServer.enabled .Values.ceemsAPIServer.grafana.datasource.create }}
{{- $basicAuthEnabled := (and (hasKey .Values.ceemsAPIServer.grafana.datasource.basicAuth "username") (hasKey .Values.ceemsAPIServer.grafana.datasource.basicAuth "password")) -}}
{{- $authHeaderEnabled := (and (hasKey .Values.ceemsAPIServer.grafana.datasource.authHeader "name") (hasKey .Values.ceemsAPIServer.grafana.datasource.authHeader "value")) -}}
{{- $tlsEnabled := (and (hasKey .Values.ceemsAPIServer.grafana.datasource.tls "clientCert") (hasKey .Values.ceemsAPIServer.grafana.datasource.tls "clientKey")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-ceems.api-server.fullname" . }}-grafana-ds
  namespace: {{ include "kube-ceems.api-server.namespace" . }}
  labels:
    {{ tpl .Values.kubePrometheusStackGrafana.sidecar.datasources.label . }}: {{ tpl .Values.kubePrometheusStackGrafana.sidecar.datasources.labelValue . }}
    {{- include "kube-ceems.api-server.labels" $ | nindent 4 }}
stringData:
  ceems-api-server.yaml: |-
    apiVersion: 1
    datasources:
      - name: {{ template "kube-ceems.api-server.fullname" . }}
        type: yesoreyeram-infinity-datasource
        url: {{ .Values.ceemsAPIServer.grafana.datasource.scheme }}://{{ template "kube-ceems.api-server.fullname" . }}.{{ template "kube-ceems.api-server.namespace" . }}:{{ .Values.ceemsAPIServer.service.port }}
{{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ .Values.ceemsAPIServer.grafana.datasource.basicAuth.username }}
{{- end }}
        jsonData:
{{- if $basicAuthEnabled }}
          auth_method: basicAuth
{{- end }}
          tlsSkipVerify: {{ .Values.ceemsAPIServer.grafana.datasource.tls.skipVerify | default false }}
          tlsAuth: {{ .Values.ceemsAPIServer.grafana.datasource.tls.authEnabled | default false }}
          tlsAuthWithCACert: {{ .Values.ceemsAPIServer.grafana.datasource.tls.authWithCACert | default false }}
          timeout: 120
          allowedHosts:
            - {{ .Values.ceemsAPIServer.grafana.datasource.scheme }}://{{ template "kube-ceems.api-server.fullname" . }}.{{ template "kube-ceems.api-server.namespace" . }}:{{ .Values.ceemsAPIServer.service.port }}
          httpHeaderName1: X-Grafana-User
{{- if $authHeaderEnabled }}
          httpHeaderName2: {{ .Values.ceemsAPIServer.grafana.datasource.authHeader.name }}
{{- end }}
        secureJsonData:
          # This will be replaced by username before passing to API server
          # This feature is available only for yesoreyeram-infinity-datasource >= 3.x
          # IMPORTANT: Need $$ to escape $
          httpHeaderValue1: $${__user.login}
{{- if $basicAuthEnabled }}
          basicAuthPassword: {{ .Values.ceemsAPIServer.grafana.datasource.basicAuth.password }}
{{- end }}
{{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ .Values.ceemsAPIServer.grafana.datasource.authHeader.value }}
{{- end }}
{{- if $tlsEnabled }}
          tlsCACert: {{ .Values.ceemsAPIServer.grafana.datasource.tls.caCert | toYaml | indent 10 }}
          tlsClientCert: {{ .Values.ceemsAPIServer.grafana.datasource.tls.clientCert | toYaml | indent 10 }}
          tlsClientKey: {{ .Values.ceemsAPIServer.grafana.datasource.tls.clientKey | toYaml | indent 10 }}
{{- end }}
{{- end }}
