apiVersion: v2
name: kube-ceems
description: A Helm chart for deploying CEEMS
icon: https://raw.githubusercontent.com/ceems-dev/ceems/main/website/static/img/logo.png
keywords:
  - ceems-exporter
  - ceems-api-server
  - ceems-lb
  - prometheus
  - exporter
  - ceems
  - monitoring
  - gpu
  - nvidia
  - amd
  - energy
  - emissions
  - performance
  - io
  - network
  - ebpf
type: application
version: 0.4.0
# renovate: github=ceems-dev/ceems
appVersion: 0.11.2
home: https://ceems-dev.github.io/helm-charts/
sources:
  - https://github.com/ceems-dev/helm-charts
maintainers:
  - name: mahendrapaipuri
    email: mahendra.paipuri@gmail.com
    url: https://github.com/mahendrapaipuri
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/ceems-dev/helm-charts
    - name: Upstream Project
      url: https://github.com/ceems-dev/ceems
dependencies:
  - name: kube-prometheus-stack
    version: "77.10.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubePrometheusStack.enabled
    import-values:
      - child: grafana
        parent: kubePrometheusStackGrafana
  - name: pyroscope
    version: "1.15.0"
    repository: https://grafana.github.io/helm-charts
    condition: pyroscopeServer.enabled
