{{- if and .Values.ceemsExporter.enabled .Values.pyroscopeServer.enabled (index .Values "ceems-exporter" "eBPFProfiling" "enabled") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-exporter.fullname" (index .Subcharts "ceems-exporter") }}-grafana-ds
  namespace: {{ include "ceems-exporter.namespace" (index .Subcharts "ceems-exporter") }}
  labels:
    {{ tpl (index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label") . }}: {{ tpl (index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "labelValue") . }}
    {{- include "ceems-exporter.labels" (index .Subcharts "ceems-exporter") | nindent 4 }}
stringData:
  ceems-pyroscope.yaml: |-
    apiVersion: 1
    datasources:
      - name: {{ template "kube-ceems.pyroscope-ds-name" . }}
        type: grafana-pyroscope-datasource
        access: proxy
        url: {{ template "kube-ceems.pyroscope-svc-url" . }}
        isDefault: false
{{- end }}
