{{- if and .Values.ceemsExporter.enabled .Values.ceemsExporter.eBPFProfiling.enabled .Values.pyroscopeServer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-ceems.exporter.fullname" . }}-grafana-ds
  namespace: {{ include "kube-ceems.exporter.namespace" . }}
  labels:
    {{ tpl .Values.kubePrometheusStackGrafana.sidecar.datasources.label . }}: {{ tpl .Values.kubePrometheusStackGrafana.sidecar.datasources.labelValue . }}
    {{- include "kube-ceems.exporter.labels" $ | nindent 4 }}
stringData:
  ceems-pyroscope.yaml: |-
    apiVersion: 1
    datasources:
      - name: {{ template "kube-ceems.pyroscope-ds-name" . }}
        type: grafana-pyroscope-datasource
        access: proxy
        url: {{ template "kube-ceems.pyroscope-svc-url" . }}
        isDefault: false
{{- end }}
