---

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md013.md
MD013:
  line_length: 800

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md033.md
MD033:
  allowed_elements:
    - td
    - div
    - tr
    - pre
    - a
    - code
    - table
    - thead
    - th
    - tbody

# MD034/no-bare-urls : Bare URL used : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md034.md
MD034: false

# Allow hard tabs
no-hard-tabs: false

# Allow blanks-around-fences
blanks-around-fences: false
