---
chart-dirs:
  - charts
chart-repos:
  - pyroscope=https://grafana.github.io/helm-charts
  - kube-prometheus-stack=https://prometheus-community.github.io/helm-charts
github-groups: true
helm-extra-args: --timeout 600s
remote: origin
target-branch: main
use-helmignore: true
validate-maintainers: false 
