{{- if .Values.ceemsAPIServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kube-ceems.fullname" . }}-admission-controller-web-config
  namespace: {{ include "kube-ceems.namespace" . }}
data:
  web-config.yaml: |+
    tls_server_config:
      cert_file: /certs/tls.crt
      key_file: /certs/tls.key
{{- end }}
