{
 "title": "Single Job Metrics",
 "description": "Time series metrics of a SLURM job",
 "tags": [
  "slurm",
  "emissions",
  "energy",
  "batch"
 ],
 "time": { "from": "2025-02-07T15:58:19.000Z", "to": "2025-02-07T16:05:03.000Z" },
 "templating": {
  "list": [
   { "name": "jobid", "label": "JobID" },
   {
    "name": "host",
    "label": "Compute Node:",
    "query": {
     "query": "label_values(ceems_compute_unit_cpus{uuid=\"$jobid\"},instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU:",
    "query": {
     "query": "query_result(max_over_time(ceems_compute_unit_gpu_index_flag{instance=~\"${host}\",uuid=\"${jobid}\"}[$__range:]))"
    }
   },
   { "name": "name" },
   { "name": "submit", "query": "1738943876000" },
   { "name": "nodelist" },
   { "name": "state" },
   { "name": "elapsed" },
   { "name": "account" },
   { "name": "partition" },
   { "name": "qos" },
   { "name": "cpu_usage" },
   { "name": "cpumem_usage" },
   { "name": "cpu_energy" },
   { "name": "cpu_emissions_rte" },
   { "name": "cpu_emissions_emaps" },
   { "name": "cpu_emissions_wt" },
   { "name": "cpu_emissions_owid" },
   { "name": "cpu_emissions_global" },
   { "name": "gpu_usage" },
   { "name": "gpumem_usage" },
   { "name": "gpu_energy" },
   { "name": "gpu_emissions_rte" },
   { "name": "gpu_emissions_emaps" },
   { "name": "gpu_emissions_wt" },
   { "name": "gpu_emissions_owid" },
   { "name": "gpu_emissions_global" },
   { "name": "total_energy" },
   { "name": "total_emissions_rte" },
   { "name": "total_emissions_emaps" },
   { "name": "total_emissions_wt" },
   { "name": "total_emissions_owid" },
   { "name": "total_emissions_global" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<span> \n  The following metrics are aggregated over entire job duration\n</span>\n<br>\n<br>\n\n<table><tbody>\n  <tr>\n    <th rowspan=\"4\">Average Utilization (%)</th>\n    <th>CPU</th>\n    <td colspan=\"5\">${cpu_usage}</td>\n  </tr>\n  <tr>\n    <th>CPU Memory</th>\n    <td colspan=\"5\">${cpumem_usage}</td>\n  </tr>\n  <tr>\n    <th>GPU</th>\n    <td colspan=\"5\">${gpu_usage}</td>\n  </tr>\n  <tr>\n    <th>GPU Memory</td>\n    <td colspan=\"5\">${gpumem_usage}</td>\n  </tr>\n  <tr>\n    <th rowspan=\"3\">Energy Consumption (kWh)</th>\n    <th>Host</th>\n    <td colspan=\"5\">${cpu_energy}</td>\n  </tr>\n  <tr>\n    <th>GPU</th>\n    <td colspan=\"5\">${gpu_energy}</td>\n  </tr>\n  <tr>\n    <th>Total</th>\n    <td colspan=\"5\">${total_energy}</td>\n  </tr>\n  <tr>\n    <th rowspan=\"6\">Equivalent Emissions (gms)</th>\n    <th>Emission Factor</th>\n    <th>RTE</th>\n    <th>Elec. Maps</th>\n    <th>W. Time</th>\n    <th>OWID</th>\n    <th>World Avg.</th>\n  </tr>\n  <tr>\n    <th>Host</th>\n    <td>${cpu_emissions_rte}</td>\n    <td>${cpu_emissions_emaps}</td>\n    <td>${cpu_emissions_wt}</td>\n    <td>${cpu_emissions_owid}</td>\n    <td>${cpu_emissions_global}</td>\n  </tr>\n  <tr>\n    <th>GPU</th>\n    <td>${gpu_emissions_rte}</td>\n    <td>${gpu_emissions_emaps}</td>\n    <td>${gpu_emissions_wt}</td>\n    <td>${gpu_emissions_owid}</td>\n    <td>${gpu_emissions_global}</td>\n  </tr>\n  <tr>\n    <th>Total</th>\n    <td>${total_emissions_rte}</td>\n    <td>${total_emissions_emaps}</td>\n    <td>${total_emissions_wt}</td>\n    <td>${total_emissions_owid}</td>\n    <td>${total_emissions_global}</td>\n  </tr>\n</tbody></table>"
   }
  },
  {
   "title": "Job Details",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<span> \n  Following table gives different job meta data\n</span>\n<br>\n<br>\n\n<table width=\"100%\">\n  <thead>\n    <tr>\n      <th scope=\"col\">Attribute</th>\n      <th scope=\"col\">Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th scope=\"row\">ID</th>\n      <td>${jobid}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Name</th>\n      <td>${name}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Account</th>\n      <td>${account}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Partition</th>\n      <td>${partition}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">QoS</th>\n      <td>${qos}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Submit Time</th>\n      <td>${submit:date:YYYY-MM-DD HH:mm:SS Z}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Start Time</th>\n      <td>${__from:date:YYYY-MM-DD HH:mm:SS Z}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">End Time</th>\n      <td>${__to:date:YYYY-MM-DD HH:mm:SS Z}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Elapsed Time</th>\n      <td>${elapsed}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">State</th>\n      <td>${state}</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Nodelist</th>\n      <td>${nodelist}</td>\n    </tr>\n  </tbody>\n</table>\n"
   }
  },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "This dashboard presents the time series metrics of job ${jobid} submitted using project ${account}.\nCurrently the following time series metrics are available:\n\n- **CPU Stats**:\n\n    - *CPU Usage*: This shows the usage of CPU by the job and it is estimated using CPU time.\n        In one second interval, if CPU works only for 0.2 seconds, CPU usage will be reported as 20%. \n        If a job allocates _n_ cpus and uses all _n_\n        cpus all the time, the usage will be 100% all the time. If the job uses only _n/2_ cpus or uses\n        _n_ cpus only 50% of time, the resulting CPU usage will be 50%.\n\n    - *CPU Memory Usage*: This is the percentage of memory used by the job compared to the memory available\n        within SLURM job.\n\n    - *Host Energy Usage*: This is the energy consumption estimated based on total energy consumption\n        (excluding GPUs) of the\n        compute node and the resources used by the job. Thus it includes CPU, CPU memory and other peripherals \n        on the compute node excluding GPUs. The estimation is made using CPU time, memory used\n        by the job relative to total CPU time and total memory used by the entire node. If there are multiple\n        jobs running on the node at a given time, the reported energy consumption is the energy consumed only\n        by the current job.\n<br />\n\n- **CPU Performance Stats**: \n\n    - *CPU Frequency*: The average frequency at which all the cores in the job allocation are running during the\n        execution of the job.\n\n    - *CPU IPC*: Instructions Per Cylce (IPC) gives number of instructions finished per CPU cycle. An IPC value of more\n        than 1 indicates a good performing code. Higher the value of IPC, better the code performance.\n\n    - *CPU Software Events*: Two different software events are presented: Context switches and CPU migrations. Context\n        switches happens when execution context changes from user mode to kernel mod or *vice-versa*. Context switch is\n        an expensive operation and hence, more context switches means lower performing code. CPU migraion happens when\n        execution of task change from one CPU core to another. Lower is better and it can be achieved using\n        [CPU pinning](https://slurm.schedmd.com/cpu_management.html).\n    \n    - *Page Faults*: Page faults happen when task access a memory region that is not \"prepared\". A minor page fault\n        happens when page is loaded into the memory but it not mapped. On the otherhand major fault happens when page\n        is not loaded in the memory. Lower is better. Minor page faults will not have huge impact on the performance\n        where as higher major page faults indicates bad memory management by the code.\n\n    - *Cache Events*: Cache events indicate the cache efficiency of the code. Currently supported events are L1 read\n        misses ratio and LL read/write misses ratio. Lower is better. L1 is first level cache with very fast access times\n        but limited size where LL is last level cache with slower access times but with larger size. A higher miss ratio\n        indicates that the code needs to fetch the data from the memory often indicates bad caching efficiency.\n<br />\n\n- **GPU Stats**:\n\n    - *GPU Usage*: This shows the GPU usage reported by [NVML](https://developer.nvidia.com/management-library-nvml).\n        According to [NVML docs](https://docs.nvidia.com/deploy/nvml-api/structnvmlUtilization__t.html#structnvmlUtilization__t),\n        it is percent of time over the past sample period during which one or more kernels was executing on the GPU.\n\n    - *GPU Memory Usage*: This is the percentage of memory used by the job compared to the available memory on\n        the GPU.\n\n    - *GPU Energy Usage*: This is the energy consumption reported by [NVML](https://developer.nvidia.com/management-library-nvml)\n        by the GPU.\n<br />\n\n- **GPU Profiling Stats**: NVIDIA DCGM [docs](https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#profiling-metrics)\nexplains all the presented GPU profiling metrics.\n<br />\n\n- **IO Stats**:\n\n    - *Read/Write bandwidths*: Read/Write bandwidths from different compute nodes for different\n        file systems.\n\n    - *Read/Write Requests*: Number of requests for read/write from different compute nodes for different \n        file systems.\n\n    - *Read/Write Errors*: Number of errors while executing read/write requests from different compute nodes\n        for different file systems.\n<br />\n\n- **Profiling**: This is very minimal/low overhead profiling of the code done using eBPF based continuous profiling tool\n. In a nutshell, the profiler samples the code\n    at a frequency and builds a histogram of data of how many times code executed in different regions of\n    the code. By resolving the regions to the function names, a flame graph is built to show the time spent\n    in each function of the code. For the better resolution of the function names, debug symbols must be\n    included in the application binaries. It is also recommended to include frame pointers using the flag\n    `-fno-omit-frame-pointer` in the compiler options. More details on how to intrepret flame graphs can be\n    found in [Grafana Pyroscope Docs](https://grafana.com/docs/pyroscope/latest/introduction/flamegraphs/)."
   }
  },
  {
   "title": "CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "Time series of CPU usage for different hosts in the job",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_cpu_usage:ratio_irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "CPU Total on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_cpu_usage:ratio_irate{uuid=\"${jobid}\"})",
       "legendFormat": "CPU Total on all nodes"
      }
     ]
    },
    {
     "title": "CPU Memory Utilization",
     "type": "timeseries",
     "description": "Time series of CPU memory usage for different hosts in the job",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ceems_compute_unit_memory_total_bytes{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Total usable on {{hostname}}"
      },
      {
       "expr": "ceems_compute_unit_memory_used_bytes{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Used on {{hostname}}"
      },
      {
       "expr": "ceems_compute_unit_memory_rss_bytes{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "RSS on {{hostname}}"
      },
      {
       "expr": "ceems_compute_unit_memory_cache_bytes{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Cached on {{hostname}}"
      },
      {
       "expr": "sum(ceems_compute_unit_memory_total_bytes{uuid=\"${jobid}\"})",
       "legendFormat": "Total usagable on all nodes"
      },
      {
       "expr": "sum(ceems_compute_unit_memory_used_bytes{uuid=\"${jobid}\"})",
       "legendFormat": "Total used on all nodes"
      },
      {
       "expr": "sum(ceems_compute_unit_memory_rss_bytes{uuid=\"${jobid}\"})",
       "legendFormat": "Total RSS on all nodes"
      },
      {
       "expr": "sum(ceems_compute_unit_memory_cache_bytes{uuid=\"${jobid}\"})",
       "legendFormat": "Total Cached on all nodes"
      }
     ]
    },
    {
     "title": "Host Power Usage",
     "type": "timeseries",
     "description": "Time series of estimated Host power usage of different compute nodes in the job",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "uuid:ceems_host_power_watts:pue{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Total consumption on {{hostname}}"
      },
      {
       "expr": "sum(uuid:ceems_host_power_watts:pue{uuid=\"${jobid}\"})",
       "legendFormat": "Total consumption on all nodes"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Performance Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Frequency",
     "type": "timeseries",
     "description": "Time series of CPU Frequency",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "irate(ceems_perf_cpucycles_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / ceems_compute_unit_cpus{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "CPU Freq. on {{hostname}}"
      },
      {
       "expr": "irate(ceems_perf_ref_cpucycles_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / ceems_compute_unit_cpus{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Ref CPU Freq. on {{hostname}}"
      }
     ]
    },
    {
     "title": "CPU IPC",
     "type": "timeseries",
     "description": "Time series of Instructions per Cycle (IPC). A value of more than 1 can be interpreted as good.",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "si:isns/cycle" } },
     "targets": [
      {
       "expr": "irate(ceems_perf_instructions_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / irate(ceems_perf_cpucycles_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "CPU IPC on {{hostname}}"
      },
      {
       "expr": "sum(irate(ceems_perf_instructions_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / irate(ceems_perf_cpucycles_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Total CPU IPC"
      }
     ]
    },
    {
     "title": "CPU Software Events",
     "type": "timeseries",
     "description": "Time series of CPU Software Events",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(ceems_perf_context_switches_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "Context Switches on {{hostname}}"
      },
      {
       "expr": "irate(ceems_perf_cpu_migrations_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "CPU Migrations on {{hostname}}"
      },
      {
       "expr": "sum(irate(ceems_perf_context_switches_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Total Context Switches"
      },
      {
       "expr": "sum(irate(ceems_perf_cpu_migrations_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Total CPU Migrations"
      }
     ]
    },
    {
     "title": "Page Fault Events",
     "type": "timeseries",
     "description": "Time series of Page Fault Events. Major fault happens when memory needs to be fetched from disk where as minor fault happens when memory needs to be mapped. Higher major faults means bad memory performance. Minor faults do not have huge performance impact.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(ceems_perf_major_faults_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "Major Faults on {{hostname}}"
      },
      {
       "expr": "irate(ceems_perf_minor_faults_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "Minor Faults on {{hostname}}"
      },
      {
       "expr": "sum(irate(ceems_perf_major_faults_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Total Major Faults"
      },
      {
       "expr": "sum(irate(ceems_perf_minor_faults_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Total Minor Faults"
      }
     ]
    },
    {
     "title": "CPU Cache Events",
     "type": "timeseries",
     "description": "Time series of Cache events. L1 is the smallest and fastest cache whereas LL is the largest and slowest cache. Misses is the percentage of times that data is not found on L1/LL cache and it needs to be fetched from higher caches/memory. A smaller value means the program is using the cache efficiently. A higher value indicates a memory bound program.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(ceems_perf_cache_l1d_read_misses_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) * 100 / irate(ceems_perf_cache_l1d_read_hits_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "L1 Data Read Misses on {{hostname}}"
      },
      {
       "expr": "irate(ceems_perf_cache_ll_read_misses_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / irate(ceems_perf_cache_ll_read_hits_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "LL Data Read Misses on {{hostname}}"
      },
      {
       "expr": "irate(ceems_perf_cache_ll_write_misses_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / irate(ceems_perf_cache_ll_write_hits_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval])",
       "legendFormat": "LL Data Write Misses on {{hostname}}"
      },
      {
       "expr": "avg(irate(ceems_perf_cache_l1d_read_misses_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) * 100 / irate(ceems_perf_cache_l1d_read_hits_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Avg L1 Data Read Misses"
      },
      {
       "expr": "avg(irate(ceems_perf_cache_ll_read_misses_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / irate(ceems_perf_cache_ll_read_hits_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Avg LL Data Read Misses"
      },
      {
       "expr": "avg(irate(ceems_perf_cache_ll_write_misses_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]) / irate(ceems_perf_cache_ll_write_hits_total{instance=~\"${host}\",uuid=\"${jobid}\"}[$__rate_interval]))",
       "legendFormat": "Avg LL Data Write Misses"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "description": "Time series of GPU usage reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_usage:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_usage:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"})",
       "legendFormat": "Average Usage on all GPUs"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "timeseries",
     "description": "Time series of GPU memory usage reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_memory_usage:ratio{instance=~\"${host}\", gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_memory_usage:ratio{instance=~\"${host}\", gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"})",
       "legendFormat": "Average Memory Usage on all GPUs"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "description": "Time series of GPU power usage reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_power_watts:pue{instance=~\"${host}\", gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "sum(uuid:ceems_gpu_power_watts:pue{uuid=\"${jobid}\"})",
       "legendFormat": "Total Usage on all GPUs"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Profiling Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU SM Activity & Occupancy",
     "type": "timeseries",
     "description": "Time series of GPU SM Activity & Occupancy reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_prof_sm_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "SM Activity on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_sm_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average SM Activity on all GPUs"
      },
      {
       "expr": "uuid:ceems_gpu_prof_sm_occupancy:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "SM Occupancy GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_sm_occupancy:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average SM Occupancy on all GPUs"
      }
     ]
    },
    {
     "title": "GPU Graphics and Tensor Engines Activity",
     "type": "timeseries",
     "description": "Time series of GPU Graphics and Tensor Engines Activity reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_prof_gr_engine_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "Graphics Engine Activity on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_gr_engine_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average Graphics Engine Activity on all GPUs"
      },
      {
       "expr": "uuid:ceems_gpu_prof_pipe_tensor_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "Tensor Pipe Activity on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_pipe_tensor_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average Tensor Pipe Activity on all GPUs"
      }
     ]
    },
    {
     "title": "GPU FP Engines Activity",
     "type": "timeseries",
     "description": "Time series of GPU FP{64, 32, 16} Engines Activity reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_prof_pipe_fp64_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "FP64 Activity on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "uuid:ceems_gpu_prof_pipe_fp32_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "FP32 Activity on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "uuid:ceems_gpu_prof_pipe_fp16_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "FP16 Activity on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_pipe_fp64_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average FP64 Engine Activity on all GPUs"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_pipe_fp32_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average FP32 Engine Activity on all GPUs"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_pipe_fp16_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average FP16 Engine Activity on all GPUs"
      }
     ]
    },
    {
     "title": "GPU Memory BW Utilization",
     "type": "timeseries",
     "description": "Time series of fraction of cycles where data was sent to or received from GPU reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_prof_dram_active:ratio{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_dram_active:ratio{uuid=\"${jobid}\"})",
       "legendFormat": "Average Memory BW Utilization on all GPUs"
      }
     ]
    },
    {
     "title": "GPU NVLink Bandwidth",
     "type": "timeseries",
     "description": "Time series of GPU NVLink Bandwidth reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_prof_nvlink_tx_bytes:sum{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "Transmitted on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_nvlink_tx_bytes:sum{uuid=\"${jobid}\"})",
       "legendFormat": "Average Transmitted Bandwidth on all GPUs"
      },
      {
       "expr": "uuid:ceems_gpu_prof_nvlink_rx_bytes:sum{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "Received on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_nvlink_rx_bytes:sum{uuid=\"${jobid}\"})",
       "legendFormat": "Average Received Bandwidth on all GPUs"
      }
     ]
    },
    {
     "title": "GPU PCIe Bandwidth",
     "type": "timeseries",
     "description": "Time series of GPU PCIe Bandwidth reported by nVIDIA-DCGM for different GPUs in the job",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "uuid:ceems_gpu_prof_pcie_tx_bytes:sum{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "Transmitted on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_pcie_tx_bytes:sum{uuid=\"${jobid}\"})",
       "legendFormat": "Average Transmitted Bandwidth on all GPUs"
      },
      {
       "expr": "uuid:ceems_gpu_prof_pcie_rx_bytes:sum{instance=~\"${host}\",gpuuuid=~\"${gpu}\",uuid=\"${jobid}\"}",
       "legendFormat": "Received on GPU: {{index}} on {{hostname}}"
      },
      {
       "expr": "avg(uuid:ceems_gpu_prof_pcie_rx_bytes:sum{uuid=\"${jobid}\"})",
       "legendFormat": "Average Received Bandwidth on all GPUs"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Read/Write Bandwidth",
     "type": "timeseries",
     "description": "Time series of Read/Write Bandwidth to different file systems.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "uuid:ceems_io_read_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Read Bandwith on {{mountpoint}} from {{hostname}}"
      },
      {
       "expr": "uuid:ceems_io_write_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Write Bandwith on {{mountpoint}} from {{hostname}}"
      },
      {
       "expr": "sum by (mountpoint) (uuid:ceems_io_read_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Read Bandwith from {{mountpoint}}"
      },
      {
       "expr": "sum by (mountpoint) (uuid:ceems_io_write_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Write Bandwith from {{mountpoint}}"
      }
     ]
    },
    {
     "title": "IO Read/Write Requests",
     "type": "timeseries",
     "description": "Time series of Read/Write Requests to different file systems.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "uuid:ceems_io_read_requests:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Read Requests on {{mountpoint}} from {{hostname}}"
      },
      {
       "expr": "uuid:ceems_io_write_requests:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Write Requests on {{mountpoint}} from {{hostname}}"
      },
      {
       "expr": "sum by (mountpoint) (uuid:ceems_io_read_requests:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Read Requests on {{mountpoint}}"
      },
      {
       "expr": "sum by (mountpoint) (uuid:ceems_io_write_requests:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Write Requests on {{mountpoint}}"
      }
     ]
    },
    {
     "title": "IO Read/Write Errors",
     "type": "timeseries",
     "description": "Time series of Read/Write Errors to different file systems.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "si:errors/s" } },
     "targets": [
      {
       "expr": "uuid:ceems_io_read_errors:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Read Errors on {{mountpoint}} from {{hostname}}"
      },
      {
       "expr": "uuid:ceems_io_write_errors:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Write Errors on {{mountpoint}} from {{hostname}}"
      },
      {
       "expr": "sum by (mountpoint) (uuid:ceems_io_read_errors:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Read Errors on {{mountpoint}}"
      },
      {
       "expr": "sum by (mountpoint) (uuid:ceems_io_write_errors:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Write Errors on {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Ingress/Egress Bandwidth",
     "type": "timeseries",
     "description": "Time series of Job Network Ingress/Egress Bandwidth.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "uuid:ceems_net_ingress_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Ingress Bandwith {{proto}}/{{family}} on {{hostname}}"
      },
      {
       "expr": "uuid:ceems_net_egress_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Egress Bandwith {{proto}}/{{family}} on {{hostname}}"
      },
      {
       "expr": "sum by (proto,family) (uuid:ceems_net_ingress_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Ingress Bandwith {{proto}}/{{family}}"
      },
      {
       "expr": "sum by (proto,family) (uuid:ceems_net_egress_bytes:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Egress Bandwith {{proto}}/{{family}}"
      }
     ]
    },
    {
     "title": "Network Ingress/Egress Packets",
     "type": "timeseries",
     "description": "Time series of Job Network Ingress/Egress Packets.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "uuid:ceems_net_ingress_packets:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Ingress Packets {{proto}}/{{family}} on {{hostname}}"
      },
      {
       "expr": "uuid:ceems_net_egress_packets:irate{instance=~\"${host}\",uuid=\"${jobid}\"}",
       "legendFormat": "Egress Packets {{proto}}/{{family}} on {{hostname}}"
      },
      {
       "expr": "sum by (proto,family) (uuid:ceems_net_ingress_packets:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Ingress Packets {{proto}}/{{family}}"
      },
      {
       "expr": "sum by (proto,family) (uuid:ceems_net_egress_packets:irate{instance=~\"${host}\",uuid=\"${jobid}\"})",
       "legendFormat": "Total Egress Packets {{proto}}/{{family}}"
      }
     ]
    }
   ]
  }
 ]
}