apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}-config
  namespace: {{ include "ceems-lb.namespace" (index .Subcharts "ceems-lb") }}
data:
  config.yaml: {{ include "kube-ceems.lb.config" . | b64enc }}
