{{- $values := (index .Values "ceems-lb") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}
  namespace: {{ include "ceems-lb.namespace" (index .Subcharts "ceems-lb") }}
  labels:
    {{- include "ceems-lb.labels" (index .Subcharts "ceems-lb") | nindent 4 }}
  {{- with $values.deployAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ceems-lb.selectorLabels" (index .Subcharts "ceems-lb") | nindent 6 }}
  revisionHistoryLimit: {{ $values.revisionHistoryLimit }}
  {{- with $values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ceems-lb.labels" (index .Subcharts "ceems-lb") | nindent 8 }}
        {{- with $values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ ternary true false (or $values.serviceAccount.automountServiceAccountToken $values.kubeRBACProxy.enabled) }}
      {{- with $values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with $values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ceems-lb.serviceAccountName" (index .Subcharts "ceems-lb") }}
      {{- with $values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        {{- $servicePortTSDB := ternary $values.kubeRBACProxy.port $values.service.port $values.kubeRBACProxy.enabled }}
        {{- $servicePortPyro := add $servicePortTSDB 10 }}
        - name: lb
          image: {{ include "ceems-lb.image" (index .Subcharts "ceems-lb") }}
          imagePullPolicy: {{ $values.image.pullPolicy }}
          command:
            - /bin/ceems_lb
          args:
            - --web.listen-address=[$(HOST_IP)]:{{ $servicePortTSDB }}
            {{- if (contains "pyroscope" (include "kube-ceems.lb.backend-types" .)) }}
            - --web.listen-address=[$(HOST_IP)]:{{ $servicePortPyro }}
            {{- end }}
            - --config.file=/etc/ceems-lb/config.yaml
            {{- if not (empty $values.webConfig) }}
            - --web.config.file=/etc/ceems-web/config.yaml
            {{- end }}
            {{- range $_, $arg := $values.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
          {{- with $values.containerSecurityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              {{- if $values.kubeRBACProxy.enabled }}
              value: 127.0.0.1
              {{- else if $values.service.listenOnAllInterfaces }}
              value: 0.0.0.0
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
              {{- end }}
            {{- range $key, $value := $values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if eq $values.kubeRBACProxy.enabled false }}
          ports:
            - name: {{ printf "%s-tsdb" $values.service.portName | trunc 14 }}
              containerPort: {{ $values.service.port }}
              protocol: TCP
            {{- if (contains "pyroscope" (include "kube-ceems.lb.backend-types" .)) }}
            - name: {{ printf "%s-pyroscope" $values.service.portName | trunc 14 }}
              containerPort: {{ add $values.service.port 10 }}
              protocol: TCP
            {{- end }}
          {{- end }}
          livenessProbe:
            failureThreshold: {{ $values.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_lb
            initialDelaySeconds: {{ $values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $values.livenessProbe.periodSeconds }}
            successThreshold: {{ $values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ $values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ $values.readinessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_lb
            initialDelaySeconds: {{ $values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $values.readinessProbe.periodSeconds }}
            successThreshold: {{ $values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ $values.readinessProbe.timeoutSeconds }}
          {{- with $values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $values.terminationMessageParams.enabled }}
          {{- with $values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: ceems-lb-config
              mountPath: /etc/ceems-lb
            {{- if not (empty $values.webConfig) }}
            - name: ceems-lb-web-config
              mountPath: /etc/ceems-web
            {{- end }}
            {{- if ne $values.ceemsAPIServer.persistenceVolumeClaim "" }}
            - name: ceems-db
              mountPath: /var/lib/ceems_api_server
            {{- end }}
            {{- range $_, $mount := $values.extraHostVolumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              readOnly: {{ $mount.readOnly }}
              {{- with $mount.mountPropagation }}
              mountPropagation: {{ . }}
              {{- end -}}
            {{- end -}}
            {{- range $_, $mount := $values.configmaps }}
            - name: {{ tpl $mount.name $ | quote}}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
            {{- range $_, $mount := $values.secrets }}
            - name: {{ tpl $mount.name $ | quote }}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
            {{- with $values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{-  if $values.kubeRBACProxy.enabled  }}
        - name: kube-rbac-proxy-tsdb
          args:
            {{- range $_, $arg := $values.kubeRBACProxy.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
            - --secure-listen-address=:{{ $values.service.port}}
            - --upstream=http://127.0.0.1:{{ $servicePortTSDB }}/
            - --proxy-endpoints-port={{ $values.kubeRBACProxy.proxyEndpointsPort }}
            - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
            {{- if and $values.kubeRBACProxy.tls.enabled $values.tlsSecret.enabled }}
            - --tls-cert-file=/tls/private/{{ $values.tlsSecret.certItem }}
            - --tls-private-key-file=/tls/private/{{ $values.tlsSecret.keyItem }}
            {{- if and $values.kubeRBACProxy.tls.tlsClientAuth $values.tlsSecret.caItem }}
            - --client-ca-file=/tls/private/{{ $values.tlsSecret.caItem }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- if and $values.kubeRBACProxy.tls.enabled $values.tlsSecret.enabled }}
            - name: {{ tpl $values.tlsSecret.volumeName . | quote }}
              mountPath: /tls/private
              readOnly: true
            {{- end }}
            {{- with $values.kubeRBACProxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ $values.kubeRBACProxy.image.pullPolicy }}
          {{- if $values.kubeRBACProxy.image.sha }}
          image: "{{ $values.imageRegistry | default $values.kubeRBACProxy.image.registry}}/{{ $values.kubeRBACProxy.image.repository }}:{{ $values.kubeRBACProxy.image.tag }}@sha256:{{ $values.kubeRBACProxy.image.sha }}"
          {{- else }}
          image: "{{ $values.imageRegistry | default $values.kubeRBACProxy.image.registry}}/{{ $values.kubeRBACProxy.image.repository }}:{{ $values.kubeRBACProxy.image.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ $values.service.port }}
              name: {{ printf "%s-tsdb" $values.kubeRBACProxy.portName | trunc 14 }}
              {{- if $values.kubeRBACProxy.enableHostPort }}
              hostPort: {{ $values.service.port }}
              {{- end }}
            - containerPort: {{ $values.kubeRBACProxy.proxyEndpointsPort }}
              {{- if $values.kubeRBACProxy.enableProxyEndpointsHostPort }}
              hostPort: {{ $values.kubeRBACProxy.proxyEndpointsPort }}
              {{- end }}
              name: {{ trunc 14 "http-healthz-tsbd" }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ $values.kubeRBACProxy.proxyEndpointsPort }}
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if $values.kubeRBACProxy.resources }}
          resources:
          {{- toYaml $values.kubeRBACProxy.resources | nindent 12 }}
          {{- end }}
          {{- if $values.terminationMessageParams.enabled }}
          {{- with $values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          {{- with $values.kubeRBACProxy.env }}
          env:
            {{- range $key, $value := $values.kubeRBACProxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if $values.kubeRBACProxy.containerSecurityContext }}
          securityContext:
          {{- toYaml $values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
        {{- if (contains "pyroscope" (include "kube-ceems.lb.backend-types" .)) }}
        {{- $servicePort := add $values.service.port 10 }}
        {{- $proxyPort := add $values.kubeRBACProxy.proxyEndpointsPort 10 }}
        - name: kube-rbac-proxy-pyroscope
          args:
            {{-  if $values.kubeRBACProxy.extraArgs  }}
            {{- $values.kubeRBACProxy.extraArgs | toYaml | nindent 12 }}
            {{-  end  }}
            - --secure-listen-address=:{{ $servicePort }}
            - --upstream=http://127.0.0.1:{{ $servicePortPyro }}/
            - --proxy-endpoints-port={{ $proxyPort }}
            - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
            {{- if and $values.kubeRBACProxy.tls.enabled $values.tlsSecret.enabled }}
            - --tls-cert-file=/tls/private/{{ $values.tlsSecret.certItem }}
            - --tls-private-key-file=/tls/private/{{ $values.tlsSecret.keyItem }}
            {{- if and $values.kubeRBACProxy.tls.tlsClientAuth $values.tlsSecret.caItem }}
            - --client-ca-file=/tls/private/{{ $values.tlsSecret.caItem }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- if and $values.kubeRBACProxy.tls.enabled $values.tlsSecret.enabled }}
            - name: {{ tpl $values.tlsSecret.volumeName . | quote }}
              mountPath: /tls/private
              readOnly: true
            {{- end }}
            {{- with $values.kubeRBACProxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ $values.kubeRBACProxy.image.pullPolicy }}
          {{- if $values.kubeRBACProxy.image.sha }}
          image: "{{ $values.imageRegistry | default $values.kubeRBACProxy.image.registry}}/{{ $values.kubeRBACProxy.image.repository }}:{{ $values.kubeRBACProxy.image.tag }}@sha256:{{ $values.kubeRBACProxy.image.sha }}"
          {{- else }}
          image: "{{ $values.imageRegistry | default $values.kubeRBACProxy.image.registry}}/{{ $values.kubeRBACProxy.image.repository }}:{{ $values.kubeRBACProxy.image.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ $servicePort }}
              name: {{ printf "%s-pyroscope" $values.kubeRBACProxy.portName | trunc 14 }}
              {{- if $values.kubeRBACProxy.enableHostPort }}
              hostPort: {{ $servicePort }}
              {{- end }}
            - containerPort: {{ $proxyPort }}
              {{- if $values.kubeRBACProxy.enableProxyEndpointsHostPort }}
              hostPort: {{ $proxyPort }}
              {{- end }}
              name: {{ trunc 14 "http-healthz-pyroscope" }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ $proxyPort }}
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if $values.kubeRBACProxy.resources }}
          resources:
          {{- toYaml $values.kubeRBACProxy.resources | nindent 12 }}
          {{- end }}
          {{- if $values.terminationMessageParams.enabled }}
          {{- with $values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          {{- with $values.kubeRBACProxy.env }}
          env:
            {{- range $key, $value := $values.kubeRBACProxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if $values.kubeRBACProxy.containerSecurityContext }}
          securityContext:
          {{ toYaml $values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if or $values.imagePullSecrets $values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "ceems-lb.imagePullSecrets" (dict "Values" $values.ceemsLB "imagePullSecrets" $values.imagePullSecrets) | indent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ceems-lb-config
          secret:
            secretName: {{ template "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}-config
        {{- if not (empty $values.webConfig) }}
        - name: ceems-lb-web-config
          secret:
            secretName: {{ template "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}-web-config
        {{- end }}
        {{- if ne $values.ceemsAPIServer.persistenceVolumeClaim "" }}
        - name: ceems-db
          persistentVolumeClaim:
            claimName: {{ tpl $values.ceemsAPIServer.persistenceVolumeClaim . }}
            readOnly: true
        {{- end }}
        {{- range $_, $mount := $values.extraHostVolumeMounts }}
        - name: {{ $mount.name }}
          hostPath:
            path: {{ $mount.hostPath }}
            {{- with $mount.type }}
            type: {{ . }}
            {{- end }}
        {{- end -}}
        {{- range $_, $mount := $values.configmaps }}
        - name: {{ tpl $mount.name $ | quote }}
          configMap:
            name: {{ tpl $mount.name $ | quote }}
        {{- end }}
        {{- range $_, $mount := $values.secrets }}
        - name: {{ tpl $mount.name $ | quote }}
          secret:
            secretName: {{ tpl $mount.name $ | quote }}
        {{- end }}
        {{- if $values.kubeRBACProxy.enabled }}
        - name: kube-rbac-proxy-config
          configMap:
            name: {{ template "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}-rbac-config
        {{- end }}
        {{- if $values.tlsSecret.enabled }}
        - name: {{ tpl $values.tlsSecret.volumeName . | quote }}
          secret:
            secretName: {{ tpl $values.tlsSecret.secretName . | quote }}
            items:
              - key: {{ required "Value tlsSecret.certItem must be set." $values.tlsSecret.certItem | quote }}
                path: {{ $values.tlsSecret.certItem | quote }}
              - key: {{ required "Value tlsSecret.keyItem must be set." $values.tlsSecret.keyItem | quote }}
                path: {{ $values.tlsSecret.keyItem | quote }}
              {{- if $values.tlsSecret.caItem }}
              - key: {{ $values.tlsSecret.caItem | quote }}
                path: {{ $values.tlsSecret.caItem | quote }}
              {{- end }}
        {{- end }}
        {{- with $values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
