{{- if and .Values.ceemsLB.enabled (index .Values "ceems-lb" "grafana" "datasource" "create") (or (index .Values "ceems-api-server" "monitoring" "enabled") (hasKey (index .Values "ceems-lb" "config") "backends")) }}
{{- $basicAuthEnabled := (and (hasKey (index .Values "ceems-lb" "grafana" "datasource" "basicAuth") "username") (hasKey (index .Values "ceems-lb" "grafana" "datasource" "basicAuth") "password")) -}}
{{- $authHeaderEnabled := (and (hasKey (index .Values "ceems-lb" "grafana" "datasource" "authHeader") "name") (hasKey (index .Values "ceems-lb" "grafana" "datasource" "authHeader") "value")) -}}
{{- $tlsEnabled := (and (hasKey (index .Values "ceems-lb" "grafana" "datasource" "tls") "clientCert") (hasKey (index .Values "ceems-lb" "grafana" "datasource" "tls") "clientKey")) -}}
{{- $backendids := list -}}
{{- $clusterid := (include "kube-ceems.cluster-id" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}-grafana-ds
  namespace: {{ include "ceems-lb.namespace" (index .Subcharts "ceems-lb") }}
  labels:
    {{ tpl (index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label") . }}: {{ tpl (index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "labelValue") . }}
    {{- include "ceems-lb.labels" (index .Subcharts "ceems-lb") | nindent 4 }}
stringData:
  ceems-lb.yaml: |-
    apiVersion: 1
    datasources:
    {{- range $key, $value := (index .Values "ceems-lb" "config" "backends") }}
    {{- $backendids = append $backendids $value.id -}}
    {{- if (hasKey $value "tsdb") }}
      - name: {{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}-{{ $value.id }}-tsdb
        type: prometheus
        url: {{ index $.Values "ceems-lb" "grafana" "datasource" "scheme" }}://{{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}.{{ template "ceems-lb.namespace" (index $.Subcharts "ceems-lb") }}:{{ index $.Values "ceems-lb" "service" "port" }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "username" }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "name" }}
      {{- end }}
          tlsSkipVerify: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "skipVerify") | default false }}
          tlsAuth: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authEnabled") | default false }}
          tlsAuthWithCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authWithCACert") | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $value.id }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "password" }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "value" }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "caCert") | toYaml | indent 10 }}
          tlsClientCert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientCert") | toYaml | indent 10 }}
          tlsClientKey: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientKey") | toYaml | indent 10 }}
      {{- end }}
    {{- end }}
    {{- if (hasKey $value "pyroscope") }}
      - name: {{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}-{{ $value.id }}-pyroscope
        type: grafana-pyroscope-datasource
        url: {{ index $.Values "ceems-lb" "grafana" "datasource" "scheme" }}://{{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}.{{ template "ceems-lb.namespace" (index $.Subcharts "ceems-lb") }}:{{ add (index $.Values "ceems-lb" "service" "port") 10 }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "username" }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "name" }}
      {{- end }}
          tlsSkipVerify: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "skipVerify") | default false }}
          tlsAuth: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authEnabled") | default false }}
          tlsAuthWithCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authWithCACert") | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $value.id }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "password" }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "value" }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "caCert") | toYaml | indent 10 }}
          tlsClientCert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientCert") | toYaml | indent 10 }}
          tlsClientKey: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientKey") | toYaml | indent 10 }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if and (index .Values "ceems-api-server" "monitoring" "enabled") (not (has $clusterid $backendids)) }}
      - name: {{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}-{{ $clusterid }}-tsdb
        type: prometheus
        url: {{ index $.Values "ceems-lb" "grafana" "datasource" "scheme" }}://{{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}.{{ template "ceems-lb.namespace" (index $.Subcharts "ceems-lb") }}:{{ index $.Values "ceems-lb" "service" "port" }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "username" }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "name" }}
      {{- end }}
          tlsSkipVerify: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "skipVerify") | default false }}
          tlsAuth: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authEnabled") | default false }}
          tlsAuthWithCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authWithCACert") | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $clusterid }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "password" }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "value" }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "caCert") | toYaml | indent 10 }}
          tlsClientCert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientCert") | toYaml | indent 10 }}
          tlsClientKey: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientKey") | toYaml | indent 10 }}
      {{- end }}
    {{- if .Values.pyroscopeServer.enabled }}
      - name: {{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}-{{ $clusterid }}-pyroscope
        type: grafana-pyroscope-datasource
        url: {{ index $.Values "ceems-lb" "grafana" "datasource" "scheme" }}://{{ template "ceems-lb.fullname" (index $.Subcharts "ceems-lb") }}.{{ template "ceems-lb.namespace" (index $.Subcharts "ceems-lb") }}:{{ add (index $.Values "ceems-lb" "service" "port") 10 }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "username" }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "name" }}
      {{- end }}
          tlsSkipVerify: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "skipVerify") | default false }}
          tlsAuth: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authEnabled") | default false }}
          tlsAuthWithCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "authWithCACert") | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $clusterid }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ index $.Values "ceems-lb" "grafana" "datasource" "basicAuth" "password" }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ index $.Values "ceems-lb" "grafana" "datasource" "authHeader" "value" }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "caCert") | toYaml | indent 10 }}
          tlsClientCert: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientCert") | toYaml | indent 10 }}
          tlsClientKey: {{ (index $.Values "ceems-lb" "grafana" "datasource" "tls" "clientKey") | toYaml | indent 10 }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
