{{- if and .Values.ceemsLB.enabled .Values.ceemsLB.grafana.datasource.create (or .Values.monitorCurrentCluster (hasKey .Values.ceemsLB.config "backends")) }}
{{- $basicAuthEnabled := (and (hasKey .Values.ceemsLB.grafana.datasource.basicAuth "username") (hasKey .Values.ceemsLB.grafana.datasource.basicAuth "password")) -}}
{{- $authHeaderEnabled := (and (hasKey .Values.ceemsLB.grafana.datasource.authHeader "name") (hasKey .Values.ceemsLB.grafana.datasource.authHeader "value")) -}}
{{- $tlsEnabled := (and (hasKey .Values.ceemsLB.grafana.datasource.tls "clientCert") (hasKey .Values.ceemsLB.grafana.datasource.tls "clientKey")) -}}
{{- $backendids := list -}}
{{- $clusterid := (include "kube-ceems.cluster-id" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-ceems.lb.fullname" . }}-grafana-ds
  namespace: {{ include "kube-ceems.lb.namespace" . }}
  labels:
    {{ tpl .Values.kubePrometheusStackGrafana.sidecar.datasources.label . }}: {{ tpl .Values.kubePrometheusStackGrafana.sidecar.datasources.labelValue . }}
    {{- include "kube-ceems.lb.labels" $ | nindent 4 }}
stringData:
  ceems-lb.yaml: |-
    apiVersion: 1
    datasources:
    {{- range $key, $value := .Values.ceemsLB.config.backends }}
    {{- $backendids = append $backendids $value.id -}}
    {{- if (hasKey $value "tsdb") }}
      - name: {{ template "kube-ceems.lb.fullname" $ }}-{{ $value.id }}-tsdb
        type: prometheus
        url: {{ $.Values.ceemsLB.grafana.datasource.scheme }}://{{ template "kube-ceems.lb.fullname" $ }}.{{ template "kube-ceems.lb.namespace" $ }}:{{ $.Values.ceemsLB.service.port }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.username }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.name }}
      {{- end }}
          tlsSkipVerify: {{ $.Values.ceemsLB.grafana.datasource.tls.skipVerify | default false }}
          tlsAuth: {{ $.Values.ceemsLB.grafana.datasource.tls.authEnabled | default false }}
          tlsAuthWithCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.authWithCACert | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $value.id }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.password }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.value }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.caCert | toYaml | indent 10 }}
          tlsClientCert: {{ $.Values.ceemsLB.grafana.datasource.tls.clientCert | toYaml | indent 10 }}
          tlsClientKey: {{ $.Values.ceemsLB.grafana.datasource.tls.clientKey | toYaml | indent 10 }}
      {{- end }}
    {{- end }}
    {{- if (hasKey $value "pyroscope") }}
      - name: {{ template "kube-ceems.lb.fullname" $ }}-{{ $value.id }}-pyroscope
        type: grafana-pyroscope-datasource
        url: {{ $.Values.ceemsLB.grafana.datasource.scheme }}://{{ template "kube-ceems.lb.fullname" $ }}.{{ template "kube-ceems.lb.namespace" $ }}:{{ add $.Values.ceemsLB.service.port 10 }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.username }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.name }}
      {{- end }}
          tlsSkipVerify: {{ $.Values.ceemsLB.grafana.datasource.tls.skipVerify | default false }}
          tlsAuth: {{ $.Values.ceemsLB.grafana.datasource.tls.authEnabled | default false }}
          tlsAuthWithCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.authWithCACert | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $value.id }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.password }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.value }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.caCert | toYaml | indent 10 }}
          tlsClientCert: {{ $.Values.ceemsLB.grafana.datasource.tls.clientCert | toYaml | indent 10 }}
          tlsClientKey: {{ $.Values.ceemsLB.grafana.datasource.tls.clientKey | toYaml | indent 10 }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if and .Values.monitorCurrentCluster (not (has $clusterid $backendids)) }}
      - name: {{ template "kube-ceems.lb.fullname" . }}-{{ $clusterid }}-tsdb
        type: prometheus
        url: {{ $.Values.ceemsLB.grafana.datasource.scheme }}://{{ template "kube-ceems.lb.fullname" . }}.{{ template "kube-ceems.lb.namespace" . }}:{{ $.Values.ceemsLB.service.port }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.username }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.name }}
      {{- end }}
          tlsSkipVerify: {{ $.Values.ceemsLB.grafana.datasource.tls.skipVerify | default false }}
          tlsAuth: {{ $.Values.ceemsLB.grafana.datasource.tls.authEnabled | default false }}
          tlsAuthWithCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.authWithCACert | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $clusterid }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.password }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.value }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.caCert | toYaml | indent 10 }}
          tlsClientCert: {{ $.Values.ceemsLB.grafana.datasource.tls.clientCert | toYaml | indent 10 }}
          tlsClientKey: {{ $.Values.ceemsLB.grafana.datasource.tls.clientKey | toYaml | indent 10 }}
      {{- end }}
    {{- if .Values.pyroscopeServer.enabled }}
      - name: {{ template "kube-ceems.lb.fullname" . }}-{{ $clusterid }}-pyroscope
        type: grafana-pyroscope-datasource
        url: {{ $.Values.ceemsLB.grafana.datasource.scheme }}://{{ template "kube-ceems.lb.fullname" . }}.{{ template "kube-ceems.lb.namespace" . }}:{{ add $.Values.ceemsLB.service.port 10 }}
        access: proxy
      {{- if $basicAuthEnabled }}
        basicAuth: true
        basicAuthUser: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.username }}
      {{- end }}
        jsonData:
          httpHeaderName1: X-Ceems-Cluster-Id
      {{- if $authHeaderEnabled }}
          httpHeaderName2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.name }}
      {{- end }}
          tlsSkipVerify: {{ $.Values.ceemsLB.grafana.datasource.tls.skipVerify | default false }}
          tlsAuth: {{ $.Values.ceemsLB.grafana.datasource.tls.authEnabled | default false }}
          tlsAuthWithCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.authWithCACert | default false }}
        secureJsonData:
          httpHeaderValue1: {{ $clusterid }}
      {{- if $basicAuthEnabled }}
          basicAuthPassword: {{ $.Values.ceemsLB.grafana.datasource.basicAuth.password }}
      {{- end }}
      {{- if $authHeaderEnabled }}
          httpHeaderValue2: {{ $.Values.ceemsLB.grafana.datasource.authHeader.value }}
      {{- end }}
      {{- if $tlsEnabled }}
          tlsCACert: {{ $.Values.ceemsLB.grafana.datasource.tls.caCert | toYaml | indent 10 }}
          tlsClientCert: {{ $.Values.ceemsLB.grafana.datasource.tls.clientCert | toYaml | indent 10 }}
          tlsClientKey: {{ $.Values.ceemsLB.grafana.datasource.tls.clientKey | toYaml | indent 10 }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
