{{- if and .Values.ceemsLB.enabled .Values.ceemsLB.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-ceems.lb.fullname" . }}
  namespace: {{ include "kube-ceems.lb.namespace" . }}
  labels:
    {{- include "kube-ceems.lb.labels" $ | nindent 4 }}
    {{- with .Values.ceemsLB.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ceemsLB.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ceemsLB.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.ceemsLB.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.ceemsLB.service.ipDualStack.ipFamilyPolicy }}
{{- end }}
{{- if .Values.ceemsLB.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.ceemsLB.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.ceemsLB.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.ceemsLB.service.internalTrafficPolicy }}
{{- end }}
  type: {{ .Values.ceemsLB.service.type }}
{{- if and (eq .Values.ceemsLB.service.type "ClusterIP") .Values.ceemsLB.service.clusterIP }}
  clusterIP: "{{ .Values.ceemsLB.service.clusterIP }}"
{{- end }}
  ports:
    {{- $port := .Values.ceemsLB.service.servicePort | default .Values.ceemsLB.service.port }}
    - port: {{ $port }}
      {{- if ( and (eq .Values.ceemsLB.service.type "NodePort" ) (not (empty .Values.ceemsLB.service.nodePort)) ) }}
      nodePort: {{ .Values.ceemsLB.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.ceemsLB.service.targetPort }}
      protocol: TCP
      name: {{ printf "%s-tsdb" .Values.ceemsLB.service.portName | trunc 14 }}
    {{- if (contains "pyroscope" (include "kube-ceems.lb.backend-types" .)) }}
    - port: {{ add $port 10 }}
      {{- if ( and (eq .Values.ceemsLB.service.type "NodePort" ) (not (empty .Values.ceemsLB.service.nodePort)) ) }}
      nodePort: {{ add .Values.ceemsLB.service.nodePort 10 }}
      {{- end }}
      {{- if or (kindIs "float64" .Values.ceemsLB.service.targetPort) (kindIs "int" .Values.ceemsLB.service.targetPort) }}
      targetPort: {{ add .Values.ceemsLB.service.targetPort 10 }}
      {{- else if kindIs "string" .Values.ceemsLB.service.targetPort }}
      targetPort: {{ printf "%s-pyroscope" .Values.ceemsLB.service.targetPort | trunc 14 }}
      {{- end }}
      protocol: TCP
      name: {{ printf "%s-pyroscope" .Values.ceemsLB.service.portName | trunc 14 }}
    {{- end }}
  selector:
    {{- include "kube-ceems.lb.selectorLabels" . | nindent 4 }}
{{- end }}
