{{- $values := (index .Values "ceems-lb") -}}
{{- if $values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ceems-lb.fullname" (index .Subcharts "ceems-lb") }}
  namespace: {{ include "ceems-lb.namespace" (index .Subcharts "ceems-lb") }}
  labels:
    {{- include "ceems-lb.labels" (index .Subcharts "ceems-lb") | nindent 4 }}
    {{- with $values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $values.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml $values.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ $values.service.ipDualStack.ipFamilyPolicy }}
{{- end }}
{{- if $values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $values.service.externalTrafficPolicy }}
{{- end }}
{{- if $values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ $values.service.internalTrafficPolicy }}
{{- end }}
  type: {{ $values.service.type }}
{{- if and (eq $values.service.type "ClusterIP") $values.service.clusterIP }}
  clusterIP: "{{ $values.service.clusterIP }}"
{{- end }}
  ports:
    {{- $port := $values.service.servicePort | default $values.service.port }}
    - port: {{ $port }}
      {{- if ( and (eq $values.service.type "NodePort" ) (not (empty $values.service.nodePort)) ) }}
      nodePort: {{ $values.service.nodePort }}
      {{- end }}
      targetPort: {{ $values.service.targetPort }}
      protocol: TCP
      name: {{ printf "%s-tsdb" $values.service.portName | trunc 14 }}
    {{- if (contains "pyroscope" (include "kube-ceems.lb.backend-types" .)) }}
    - port: {{ add $port 10 }}
      {{- if ( and (eq $values.service.type "NodePort" ) (not (empty $values.service.nodePort)) ) }}
      nodePort: {{ add $values.service.nodePort 10 }}
      {{- end }}
      {{- if or (kindIs "float64" $values.service.targetPort) (kindIs "int" $values.service.targetPort) }}
      targetPort: {{ add $values.service.targetPort 10 }}
      {{- else if kindIs "string" $values.service.targetPort }}
      targetPort: {{ printf "%s-pyroscope" $values.service.targetPort | trunc 14 }}
      {{- end }}
      protocol: TCP
      name: {{ printf "%s-pyroscope" $values.service.portName | trunc 14 }}
    {{- end }}
  selector:
    {{- include "ceems-lb.selectorLabels" (index .Subcharts "ceems-lb") | nindent 4 }}
{{- end }}
